### ISSUE TITLE
RSSBOT not working

### ISSUE THREAD

**Issue by Syndrogo** [SmBe19/RedditBots#4]
So i am running the RSSbot on python everywhere. I have loaded the RSSBot.py file and it opens up lynx panel. I dont know what to do from here. I know its not pulling from the RSS (nothing posted in the reddit.

**Comment by SmBe19** [comment]
Lynx is started because of oauth. I assume you filled out the `oauth.ini` file correctly. If you want to run the bot on a server you obviously don't have a graphical browser to accept the oauth request. You can either try [server mode](https://github.com/SmBe19/praw-OAuth2Util/blob/master/OAuth2Util/README.md#server-mode) or run the bot the first time locally and the copy the `oauth.ini` file to the server. Hope this fixes your problem.

**Comment by Syndrogo** [comment]
So I am running this on www.pythonanywhere.com. So i cant run it as a server. I also cant run it on my pc (Work) to get the file you are talking about. Is there anything else i can do?

**Comment by SmBe19** [comment]
You could try running an [old Version](https://github.com/SmBe19/RedditBots/tree/ae60c66b46590c87cbe09d11562b22973b8c3d25/RSSBot) of RSSBot which uses password authentication. There weren't any changes other than oauth since then.

No idea how you can run it using oauth using the free plan. If you have a paid account you have a ssh connection with which you can upload the `oauth.ini` file.

**Comment by Syndrogo** [comment]
I was able to run the oauth.ini on a free account. 

So running the older version i am getting this:
sources.txt not found.
check sources
